
service: serverless-es6-jest # NOTE: update this with your service name

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  iamRoleStatement:
    $ref: ./iamRoleStatement.json


functions:
  hello:
    handler: handler.helloLambda
